name: Manual workflow

on: workflow_dispatch

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download map as KMZ
        run: wget -O ./Backup/Map.kmz https://www.google.com/maps/d/kml?mid=1khDKSoOxKkahP6TJwRDAxDZG1cc
        shell: bash

      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Updating map backup" --author="Automated Backup <>"
      - name: push code to main
        run: git push
