name: Backup 1

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download original map as KMZ
        env:
          ORIGINAL_MAP_URL: ${{ secrets.ORIGINAL_MAP_URL }}
        run: wget -O ./Backup/Original.kmz "$ORIGINAL_MAP_URL"
        shell: bash

      - name: Update backup file
        run: | 
          git status
          git add ./Backup
          git -c user.name="GitHub Actions" -c user.email="none@nwkitespots.com" commit -m "Updating map backup"
          git config pull.rebase false
          git pull
          git push
